# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "experiment_type_id", # <donors_by_exp_plt>
  "patient_id", # <donors_by_exp_plt>
  "n_donors", # <donors_by_exp_plt>
  NULL
))
