# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "birth_date", # <mod_exploration_server>
  "age", # <mod_exploration_server>
  "genus_specie", # <mod_exploration_server>
  "gender", # <mod_exploration_server>
  "disease", # <mod_exploration_server>
  "sample_source", # <mod_exploration_server>
  "preservation_media", # <mod_exploration_server>
  "aliquot_id", # <mod_exploration_server>
  "patient_id", # <mod_exploration_server>
  "file_id", # <mod_exploration_server>
  "size", # <mod_exploration_server>
  ".", # <mod_exploration_server>
  "project_id", # <mod_exploration_server>
  "project_name", # <mod_exploration_server>
  "experiment_type_id", # <mod_exploration_server>
  "batch_id", # <mod_exploration_server>
  "donor_count", # <mod_exploration_server>
  "sample_id", # <mod_exploration_server>
  "extension", # <mod_exploration_server>
  "content", # <mod_exploration_server>
  "seq_instrument", # <mod_exploration_server>
  "library_source", # <mod_exploration_server>
  "library_selection", # <mod_exploration_server>
  "library_strategy", # <mod_exploration_server>
  NULL
))
